spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false  # Reduce noise in tests
  h2:
    console:
      enabled: false  # Not needed in tests

logging:
  level:
    com.kousenit.persistence: info
    org.hibernate.SQL: warn
    org.springframework.boot.autoconfigure.jdbc: warn

# Test specific settings
app:
  description: "Test environment with H2 in-memory database"
  features:
    h2-console: false
    sql-logging: false