spring:
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.kousenit.persistence: debug
    org.hibernate.SQL: debug

# Development specific settings
app:
  description: "Development environment with H2 in-memory database"
  features:
    h2-console: true
    sql-logging: true